### ISSUE TITLE
[NotAnIssue] alternative dark css theme

### ISSUE THREAD

**Issue by atomGit** [mattang687/mark-it#2]
i didn't care for the default dark theme - here's what i'm using if anyone wants it - this also divides the page into 2 columns

you need to replace `<Internal UUID>` - the Internal UUID can be found in `about:debugging#/runtime/this-firefox`

```css
@-moz-document url("moz-extension://<Internal UUID>/newTab/newTab.html") {
    /* display notes */
    html.dark, body.dark, textarea.dark {
        background-color: #252525 !important;
        color: #c8c8c8 !important;
    }

    #markdownTarget {
        width: 90% !important;
        padding-left: 1% !important;
        padding-right: 1% !important;
        font-family: unset !important;
        font-size: unset !important;
    }

    a {
        color: #97ff8d !important;
        text-decoration: none !important;
    }

    code {
        background-color: #000 !important;
        color: #ffa93b;
    }

    ul, ol {
        padding: 0 !important;
        margin-left: 20px !important;
    }

    #changeModeButton {
        background-color: #929292 !important;
        left: unset !important;
        font-family: unset !important;
        right: 33px !important;
        bottom: 90px !important;
    }

    #savingIndicator {
        bottom: 0px !important;
        left: unset !important;
        right: 0px !important;
    }

    /*columns*/
    .left {
        display: block;
        float: left;
        width: 49%;
        border-right: 2px dotted #767676;
        padding-right: 10px;
    }
    .right {
        display: block;
        float: right;
        width: 49%;
    }

    /* edit notes */
    textarea {
        width: 90% !important;
        padding-left: 5% !important;
        padding-right: 5% !important;
        font-size: unset !important;
        font-family: unset !important;
    }
}
```
there's a better way to center content instead of using padding-right/left, but i'm too lazy to look it up :)
